on:
  release:
    types: [created]

jobs:
  build-and-add-assets:
    name: Build and Add Assets to Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build project for Windows
      run: dotnet publish --configuration Release --runtime win-x64 --output ./publish/windows /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
      shell: bash

    - name: Build project for Linux
      run: dotnet publish --configuration Release --runtime linux-x64 --output ./publish/linux /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
      shell: bash

    - name: Upload Release Asset (Windows)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./publish/windows/DynuSharp.HttpTest.exe
        asset_name: DynuSharp.HttpTest-windows.exe
        asset_content_type: application/octet-stream

    - name: Upload Release Asset (Linux)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./publish/linux/DynuSharp.HttpTest
        asset_name: DynuSharp.HttpTest-linux
        asset_content_type: application/octet-stream
