on:
  release:
    types: [created]

jobs:
  build-and-add-assets:
    name: Build and Add Assets to Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build project for Windows
      run: dotnet publish --configuration Release --runtime win-x64 --output ./publish/windows /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

    - name: Build project for Linux
      run: dotnet publish --configuration Release --runtime linux-x64 --output ./publish/linux /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

    - name: Install GitHub CLI
      run: |
        sudo apt update
        sudo apt install -y gh

    - name: Upload Release Asset (Windows)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.ref_name }} ./publish/windows/DynuSharp.HttpTest.exe --clobber

    - name: Upload Release Asset (Linux)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.ref_name }} ./publish/linux/DynuSharp.HttpTest --clobber
